### ISSUE TITLE
Progress::Any documentation doesn't mention need to install output modules

### ISSUE THREAD

**Issue by scottdotjs** [perlancar/perl-Progress-Any#4]
Trying the example code given in the module synopsis causes `Can't locate Progress/Any/Output/TermProgressBar.pm in @INC...`, which was confusing until I understood that `Progress::Any::Output::TermProgressBarColor` and its colleagues need to be installed as well. It would be nice to mention that in the documentation.

Thanks for the great utility!

**Comment by perlancar** [comment]
Good suggestion, implemented in commit 7f43c2d.
